In [4]:
from gqimax.mapper import weightsss_to_lambdas
import cupy as cp
import numpy as np
%load_ext autoreload
%autoreload 2
num_qubits = 3  # 4^10 = 1,048,576 phần tử
num_terms = 5
ks = [np.random.randint(1, num_terms) for _ in range(num_qubits)]

weightsss_np = [cp.random.rand(ks[i], num_qubits, 4) * (cp.random.rand(ks[i], num_qubits, 4) > 0.5) for i in range(num_qubits)]
lambdass_np = [cp.random.rand(ks[i]) for i in range(num_qubits)]
for i in range(num_qubits):
	print(weightsss_np[i].shape, lambdass_np[i].shape)
mapped_lambdass, non_zeros_indicess = weightsss_to_lambdas(weightsss_np, lambdass_np)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
(2, 3, 4) (2,)
(4, 3, 4) (4,)
(2, 3, 4) (2,)
[10 11 14 15 26 27 30 31 36 37 39 40 41 43 52 53 55 56 57 59]


In [13]:
from gqimax.mapper import map_indices_to_indicess

In [14]:
ragged_tensor = map_indices_to_indicess(non_zeros_indicess)

In [5]:
non_zeros_indicess[0]

array([[0, 2, 2],
       [0, 2, 3],
       [0, 3, 2],
       [0, 3, 3],
       [1, 2, 2],
       [1, 2, 3],
       [1, 3, 2],
       [1, 3, 3],
       [2, 1, 0],
       [2, 1, 1],
       [2, 1, 3],
       [2, 2, 0],
       [2, 2, 1],
       [2, 2, 3],
       [3, 1, 0],
       [3, 1, 1],
       [3, 1, 3],
       [3, 2, 0],
       [3, 2, 1],
       [3, 2, 3]])

In [11]:
ragged_tensor[0]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [5]:
for i in range(3):
	print(ragged_tensor[i].shape)

(10, 3)
(6, 3)
(27, 3)
