In [1]:
from jax.experimental import sparse
import jax.numpy as jnp
import numpy as np
import polars as pl
from sojo.instructor import Instructor
from sojo.pstabilizer import PStabilizer
from sojo.utils import word_to_index, char_to_index, index_to_word, create_word_zj
%load_ext autoreload
%autoreload 2

In [2]:
ins = Instructor(4)
ins.append("h", 0)
ins.append("rx", 1, 0.78)
ins.append("h", 2)
ins.append("h", 0)
ins.append("cx", [0, 1])
ins.append("h", 2)
ins.append("h", 2)
ins.append("ry", 0, 0.56)
ins.append("cx", [1, 2])
ins.append("h", 1)
ins.append("h", 3)
ins.append("h", 3)
ins.append("h", 3)
ins.append("h", 3)
ins.append("h", 0)
ins.append("h", 1)
ins.append("h", 2)
ins.append("h", 3)
ins.append("h", 0)
ins.append("h", 2)
ins.append("cx", [1, 3])
ins.operatoring()

In [21]:
num_qubits = 3
ins = Instructor(num_qubits)
for k in range(1000):
	for i in range(num_qubits - 1):
		ins.append('cx', [i, i + 1])
	ins.append('cx', [num_qubits - 1, 0])
	for i in range(num_qubits):
		ins.append('rx', i, np.random.rand())
		ins.append('ry', i, np.random.rand())
		ins.append('rz', i, np.random.rand())

ins.operatoring()
ins.create_lut_noncx(save_npy = False)


(1000, 3, 3, 4)


In [23]:
pstabilizer = PStabilizer(0, 3)
pstabilizer.map(ins)

In [42]:
import numpy as np

# Define the list
weights = np.array([[[1, 2, 3, 4],[5,6,7,8],[9,10,11,12]], [[13, 14, 15, 16],[17,18, 19, 20],[21,22,13,24]]])
print(weights.shape)
# Stack the grids and reshape to get combinations
for weight in weights:
    
    combinations = np.stack(np.meshgrid(*weight, indexing='ij'), axis=-1).reshape(-1, len(weight))
    print(combinations)


(2, 3, 4)
[[ 1  5  9]
 [ 1  5 10]
 [ 1  5 11]
 [ 1  5 12]
 [ 1  6  9]
 [ 1  6 10]
 [ 1  6 11]
 [ 1  6 12]
 [ 1  7  9]
 [ 1  7 10]
 [ 1  7 11]
 [ 1  7 12]
 [ 1  8  9]
 [ 1  8 10]
 [ 1  8 11]
 [ 1  8 12]
 [ 2  5  9]
 [ 2  5 10]
 [ 2  5 11]
 [ 2  5 12]
 [ 2  6  9]
 [ 2  6 10]
 [ 2  6 11]
 [ 2  6 12]
 [ 2  7  9]
 [ 2  7 10]
 [ 2  7 11]
 [ 2  7 12]
 [ 2  8  9]
 [ 2  8 10]
 [ 2  8 11]
 [ 2  8 12]
 [ 3  5  9]
 [ 3  5 10]
 [ 3  5 11]
 [ 3  5 12]
 [ 3  6  9]
 [ 3  6 10]
 [ 3  6 11]
 [ 3  6 12]
 [ 3  7  9]
 [ 3  7 10]
 [ 3  7 11]
 [ 3  7 12]
 [ 3  8  9]
 [ 3  8 10]
 [ 3  8 11]
 [ 3  8 12]
 [ 4  5  9]
 [ 4  5 10]
 [ 4  5 11]
 [ 4  5 12]
 [ 4  6  9]
 [ 4  6 10]
 [ 4  6 11]
 [ 4  6 12]
 [ 4  7  9]
 [ 4  7 10]
 [ 4  7 11]
 [ 4  7 12]
 [ 4  8  9]
 [ 4  8 10]
 [ 4  8 11]
 [ 4  8 12]]
[[13 17 21]
 [13 17 22]
 [13 17 13]
 [13 17 24]
 [13 18 21]
 [13 18 22]
 [13 18 13]
 [13 18 24]
 [13 19 21]
 [13 19 22]
 [13 19 13]
 [13 19 24]
 [13 20 21]
 [13 20 22]
 [13 20 13]
 [13 20 24]
 [14 17 21]
 [14 17 22]
 [14 