In [2]:
import numpy as np
from numpy import pi,cos,sin
i = np.array([[1, 0], [0, 1]])
x = np.array([[0, 1], [1, 0]])
y = np.array([[0, -1j], [1j, 0]])
z = np.array([[1, 0], [0, -1]])
cx = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])

In [54]:
cx @ kr([z,z]) @ cx

array([[ 1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0,  1,  0],
       [ 0,  0,  0, -1]])

In [61]:
kr([1/np.sqrt(2)*(x + y), x]) @ kr([z,z])

array([[ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.70710678-0.70710678j],
       [ 0.        +0.j        ,  0.        +0.j        ,
        -0.70710678+0.70710678j,  0.        +0.j        ],
       [ 0.        +0.j        , -0.70710678-0.70710678j,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.70710678+0.70710678j,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ]])

In [62]:
kr([-1/np.sqrt(2)*(y-x), y])

array([[-0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.70710678-0.70710678j],
       [-0.        +0.j        , -0.        +0.j        ,
        -0.70710678+0.70710678j,  0.        +0.j        ],
       [ 0.        +0.j        , -0.70710678-0.70710678j,
        -0.        +0.j        ,  0.        +0.j        ],
       [ 0.70710678+0.70710678j,  0.        +0.j        ,
        -0.        +0.j        , -0.        +0.j        ]])

In [64]:
kr([x,x]) @ kr([z,z]) - kr([-y,y])

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [4]:

def kr(pauli_string):
    kron_product = pauli_string[0]
    for matrix in pauli_string[1:]:
        kron_product = np.kron(kron_product, matrix)
    return kron_product

pauli_string = [i, i]
kron_product = kr(pauli_string)
kron_product

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [41]:
a0 = kr([x, x, (cos(pi/4)*z)]) + kr([x,x,(sin(pi/4)*x)])
a1 = kr([z,z,i])
a2 = kr([z,i,(cos(pi/3)*cos(pi/4)*x)]) - cos(pi/3)*sin(pi/4)*kr([z,i,z]) - sin(pi/3)*kr([z,i,y]) 

In [50]:
p = (kr([i,i,i]) + a0) @ (kr([i,i,i]) + a1) @ (kr([i,i,i]) + a2)
p[0]/8

array([0.16161165+0.j        , 0.08838835+0.21650635j,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.1767767 +0.15309311j, 0.0517767 -0.15309311j])

In [73]:
import qiskit
from qiskit.visualization import plot_histogram
from qiskit.primitives import Sampler
import qiskit.quantum_info

qc = qiskit.QuantumCircuit(2)
qc.h(1)
qc.cx(1,0)
qc.t(1)
qc.cx(1,0)
qc.h(1)
qc.rx(pi/3, 1)
# qc.measure([0,1,2], [0,1,2])
# sampler = Sampler()
# job = sampler.run(qc)
# result = job.result()
# probabilities = result.quasi_dists[0]
# print(probabilities)
state = qiskit.quantum_info.Statevector(qc).data
print(state)
dm = np.outer(state, state.conj())
print(np.round(dm,2))

[0.56242222+0.23296291j 0.        +0.j         0.30360318-0.73296291j
 0.        +0.j        ]
[[ 0.37+0.j    0.  +0.j   -0.  +0.48j  0.  +0.j  ]
 [ 0.  +0.j    0.  +0.j    0.  +0.j    0.  +0.j  ]
 [-0.  -0.48j  0.  -0.j    0.63+0.j    0.  -0.j  ]
 [ 0.  +0.j    0.  +0.j    0.  +0.j    0.  +0.j  ]]
